#logging.file.name=log/info.log
#logging.level.root=INFO
#server.error.include-message=always
logging.level.org.zalando.logbook=TRACE
filmorate.films.popular.default-count=10
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8

