CREATE TABLE public.users
(
    user_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     varchar(32) NOT NULL,
    user_name varchar(64) NULL,
    login     varchar(32) NOT NULL,
    birthdate date        NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_login_unique UNIQUE (login)
);


CREATE TABLE public.friends
(
    user_id   bigint  NOT NULL,
    friend_id bigint  NOT NULL,
    confirmed boolean NOT NULL DEFAULT false,
    CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id),
    CONSTRAINT friends_no_self CHECK (user_id <> friend_id),
    CONSTRAINT friends_user_fk FOREIGN KEY (user_id) REFERENCES public.users (user_id),
    CONSTRAINT friends_friend_fk FOREIGN KEY (friend_id) REFERENCES public.users (user_id)
);
CREATE INDEX friends_friend_id_idx ON public.friends (friend_id);


CREATE TABLE public.genres
(
    genre_id int2        NOT NULL,
    "name"   varchar(64) NOT NULL,
    CONSTRAINT genres_pk PRIMARY KEY (genre_id)
);

CREATE TABLE public.mpa_ratings
(
    rating_id   int2         NOT NULL,
    rating_name varchar(64)  NOT NULL,
    description varchar(255) NULL,
    CONSTRAINT mpa_ratings_pk PRIMARY KEY (rating_id)
);

CREATE TABLE public.films
(
    film_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar(150) NOT NULL,
    description  varchar(200) NULL,
    release_date date         NOT NULL,
    duration     int2         NOT NULL,
    rating_id    int2         NOT NULL,
    CONSTRAINT films_check CHECK ((duration >= 0)),
    CONSTRAINT films_mpa_ratings_fk FOREIGN KEY (rating_id) REFERENCES public.mpa_ratings (rating_id)
);
CREATE INDEX films_ratings_id_idx ON public.films (rating_id);

CREATE TABLE public.films_genres
(
    film_id  int8 NOT NULL,
    genre_id int2 NOT NULL,
    CONSTRAINT film_genres_pk PRIMARY KEY (film_id, genre_id),
    CONSTRAINT film_genres_film_fk FOREIGN KEY (film_id) REFERENCES public.films (film_id),
    CONSTRAINT film_genres_genre_fk FOREIGN KEY (genre_id) REFERENCES public.genres (genre_id)
);
CREATE INDEX films_genres_genre_id_idx ON public.films_genres (genre_id);

CREATE TABLE public.films_likes
(
    film_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT films_likes_pk PRIMARY KEY (film_id, user_id),
    CONSTRAINT films_likes_film_fk FOREIGN KEY (film_id) REFERENCES public.films (film_id),
    CONSTRAINT films_likes_user_fk FOREIGN KEY (user_id) REFERENCES public.users (user_id)
);
CREATE INDEX films_likes_user_id_idx ON public.films_likes (user_id);